//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDIEMDANH
    {
        public int MaDiemDanh { get; set; }
        public int MaTaiKhoan { get; set; }
        public Nullable<int> GioBatDau { get; set; }
        public Nullable<int> GioKetThuc { get; set; }
    
        public virtual DIEMDANH DIEMDANH { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
