//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.CHITIETCONGNOes = new HashSet<CHITIETCONGNO>();
            this.HOADONs = new HashSet<HOADON>();
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public int MaKH { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoaiKH { get; set; }
        public Nullable<double> TienNo { get; set; }
        public string MaLoaiKH { get; set; }
    
        public virtual ICollection<CHITIETCONGNO> CHITIETCONGNOes { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual LOAIKHACHHANG LOAIKHACHHANG { get; set; }
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
    }
}
