//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.CHITIETKHUYENMAIs = new HashSet<CHITIETKHUYENMAI>();
        }
    
        public string MaKhuyenMai { get; set; }
        public string TenKhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayBatDauKM { get; set; }
        public Nullable<System.DateTime> NgayKetThucKM { get; set; }
    
        public virtual ICollection<CHITIETKHUYENMAI> CHITIETKHUYENMAIs { get; set; }
    }
}
