//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAINHANVIEN
    {
        public LOAINHANVIEN()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public int MaLoaiNV { get; set; }
        public string TenLoaiNV { get; set; }
    
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
