//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIKHACHHANG
    {
        public LOAIKHACHHANG()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public string MaLoaiKH { get; set; }
        public string TenLoaiKH { get; set; }
    
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
