//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH
    {
        public string MaQuyDinh { get; set; }
        public string TenQuyDinh { get; set; }
        public Nullable<double> NoiDung { get; set; }
    }
}
