//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public TAIKHOAN()
        {
            this.CHITIETDIEMDANHs = new HashSet<CHITIETDIEMDANH>();
        }
    
        public int MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual ICollection<CHITIETDIEMDANH> CHITIETDIEMDANHs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
