//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THELOAI
    {
        public THELOAI()
        {
            this.CHITIETKHUYENMAIs = new HashSet<CHITIETKHUYENMAI>();
            this.SACHes = new HashSet<SACH>();
        }
    
        public int MaTheLoai { get; set; }
        public string TenTheLoai { get; set; }
    
        public virtual ICollection<CHITIETKHUYENMAI> CHITIETKHUYENMAIs { get; set; }
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}
