//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public TONKHO()
        {
            this.CHITIETTONKHOes = new HashSet<CHITIETTONKHO>();
        }
    
        public int MaTonKho { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual ICollection<CHITIETTONKHO> CHITIETTONKHOes { get; set; }
    }
}
